* -----------------------------------------------------
* XLS2GMS 2.8      24.9.2 r64480 Released Nov 14, 2017 VS8 x86 32bit/MS Windows
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    D:\Usuarios\Juanes\Documents\Juanes\Trabajo de grado\RobustoDiego\IEEE24RTS\24BUS.xlsx
* Sheet:       wData
* Range:       $A$1:$B$10
* -----------------------------------------------------
     bus
q1   3
* -----------------------------------------------------
